baseURL = "http://censorship.ai/"
languageCode = "en-us"
title = "censorship.ai"
theme = "ananke"
SectionPagesMenu = "main"


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  github = "https://github.com/kkevsterrr/geneva"
  background_color_class = "bg-black-60"
  recent_posts_number = 3
  custom_css = ["css/style.css"]
