baseURL = "https://geneva.cs.umd.edu"
languageCode = "en-US"
DefaultContentLanguage = "en"
title = "censorship.ai"
theme = "ananke"
SectionPagesMenu = "main"


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  github = "https://github.com/kkevsterrr/geneva"
  background_color_class = "bg-black-60"
  recent_posts_number = 3
  custom_css = ["css/style.css", "css/syntax.css", "css/labels.css"]
  post_content_classes = 'avenir'
  translation_enabled = false

[markup.goldmark.renderer]
  unsafe= true

[languages]
  [languages.en]
    title = "censorship.ai"
    weight = 1
